// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-radltrSe2FQgKvKxko6Pi4Uq8EDp2lU',
    appId: '1:724736279414:web:bd232ef2595f30b04fb057',
    messagingSenderId: '724736279414',
    projectId: 'scrapsnap-d8c8d',
    authDomain: 'scrapsnap-d8c8d.firebaseapp.com',
    storageBucket: 'scrapsnap-d8c8d.firebasestorage.app',
    measurementId: 'G-R2FMDTXJH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTthQPD6XB4L3JRPJwyhoA2aD__k9cN6M',
    appId: '1:724736279414:android:690bb4be990b6ce24fb057',
    messagingSenderId: '724736279414',
    projectId: 'scrapsnap-d8c8d',
    storageBucket: 'scrapsnap-d8c8d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-radltrSe2FQgKvKxko6Pi4Uq8EDp2lU',
    appId: '1:724736279414:web:961868cbd5ed17ba4fb057',
    messagingSenderId: '724736279414',
    projectId: 'scrapsnap-d8c8d',
    authDomain: 'scrapsnap-d8c8d.firebaseapp.com',
    storageBucket: 'scrapsnap-d8c8d.firebasestorage.app',
    measurementId: 'G-G1GLXE4ZQH',
  );
}
